###########################################################
### Welcome to Beautiful Jekyll!
### This config file is meant for settings that affect your entire website. When you first
### set up your website you should go through all these settings and edit them, but after
### the initial set up you won't need to come back to this file often.
###########################################################

############################
# --- Required options --- #
############################

# Name of website
title: home

# Your name to show in the footer
author: Kaptan Data Solutions

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  "About Us": "about_us"
  "Pricing": "pricing"
  "Contact": "contact"
  

  
  Kap10 - Last Tech News :
    - 2025-05-18: "https://kaptandatasolutions.github.io/2025-05-18-KAP-TEN-LAST-TECH-NEWS/"
    - 2025-05-11: "https://kaptandatasolutions.github.io/2025-05-11-KAP-TEN-LAST-TECH-NEWS/"
    - 2025-05-03: "https://kaptandatasolutions.github.io/2025-05-03-KAP-TEN-LAST-TECH-NEWS/"
    - 2025-04-28: "https://kaptandatasolutions.github.io/2025-04-28-KAP-TEN-LAST-TECH-NEWS/"
    #- 2025-04-22: "https://kaptandatasolutions.github.io/2025-04-22-KAP-TEN-LAST-TECH-NEWS/"
    #- 2025-03-10: "https://kaptandatasolutions.github.io/2025-03-10-KAP-TEN-LAST-TECH-NEWS/"
    # - 2025-03-03: "https://kaptandatasolutions.github.io/2025-03-03-KAP-TEN-LAST-TECH-NEWS/"
    # - 2025-02-03: "https://kaptandatasolutions.github.io/2025-02-03-KAP-TEN-LAST-TECH-NEWS/"
    # - 2025-01-27: "https://kaptandatasolutions.github.io/2025-01-27-KAP-TEN-LAST-TECH-NEWS/"
    # - 2025-01-21: "https://kaptandatasolutions.github.io/2025-01-21-KAP-TEN-LAST-TECH-NEWS/" 
    # - 2025-01-06: "https://kaptandatasolutions.github.io/2025-01-06-KAP-TEN-LAST-TECH-NEWS/" 
    # - 2024-12-08: "https://kaptandatasolutions.github.io/2024-12-18-KAP-TEN-LAST-TECH-NEWS/" 
    # - 2024-12-08: "https://kaptandatasolutions.github.io/2024-12-08-KAP-TEN-LAST-TECH-NEWS/" 
    #- 2024-11-30: "https://kaptandatasolutions.github.io/2024-10-21-KAP-TEN-LAST-TECH-NEWS/"
    #- 2024-11-22: "https://kaptandatasolutions.github.io/2024-11-22-KAP-TEN-LAST-TECH-NEWS/"
    #- 2024-11-18: "https://kaptandatasolutions.github.io/2024-10-28-KAP-TEN-LAST-TECH-NEWS/"
    #- 2024-11-10: "https://kaptandatasolutions.github.io/2024-11-10-KAP-TEN-LAST-TECH-NEWS/"
    #- 2024-10-28: "https://kaptandatasolutions.github.io/2024-11-18-KAP-TEN-LAST-TECH-NEWS/"
    #- 2024-10-21: "https://kaptandatasolutions.github.io/2024-10-21-KAP-TEN-LAST-TECH-NEWS/"    
  our items:
    - Automating Viral Video Transformation with an AI-Driven Workflow: "https://kaptandatasolutions.github.io/2025-05-18-Automating-Viral-Video-Transformation-with-an-AI-Driven-Workflow/"
    - Boost Your Productivity with a 4-Step AI Method to Save Over 5 Hours Daily: "https://kaptandatasolutions.github.io/2025-05-18-Boost-Your-Productivity-with-a-4-Step-AI-Method-to-Save-Over-5-Hours-Daily/"
    - How to Supercharge Your Automations with Intelligent AI Agents: "https://kaptandatasolutions.github.io/2025-05-11-10-55-KAPTAN-DATA-SOLUTIONS-ITEMS/"
    - Unlocking Autonomous Automation - A How‑To Guide on AI Agents: "https://kaptandatasolutions.github.io/2025-05-04-KAPTAN-DATA-SOLUTIONS-ITEMS-1/"
    - Leveraging Multiple AIs for Reliable Research and Content Creation: "https://kaptandatasolutions.github.io/2025-05-04-KAPTAN-DATA-SOLUTIONS-ITEMS/"
    - Podcast - Agent2Agent (A2A) Protocol for Enhanced AI Agent Collaboration: "https://kaptandatasolutions.github.io/2025-04-14-A2A-protocol/"
    - Understanding ARL: "https://kaptandatasolutions.github.io/2024-10-24-ARL0-ARL1/"
    - Revolutionizing: "https://kaptandatasolutions.github.io/2024-10-02-Revolutionizing/"
    - Surgical Robots: "https://kaptandatasolutions.github.io/2024-10-11-Robotic-Control-Strategies-at-Ganymed-Robotics/"
    - Podcast Optimizing Control Charts: "https://kaptandatasolutions.github.io/2024-10-26-Podcast-ARL/"
    - Podcast Automated Starshot Analysis: "https://kaptandatasolutions.github.io/2024-10-09-Podcast-Starshot-By-Kaptan-data-solutions-Pylinac/"
    - Podcast Automated SPC: "https://kaptandatasolutions.github.io/2024-10-09-Podcast-SPC-By-Kaptan-data-solution/"
  Solutions:
    - CorpoRAG - Internal Generative Retrieval: "https://kaptandatasolutions.github.io/2025-03-31-Local-IA/"
    - SPC Physique Médicale: "https://kaptandatasolutions.github.io/2024-10-03-Automated-SPC-Web-Solution-for-Quality-Control-in-Radiotherapy/"
    - Chatbot: "https://kaptandatasolutions.github.io/2024-10-04-Chatbot-ansm-2023/"
    - Picket Fence: "https://kaptandatasolutions.github.io/2024-10-05-Picket-Fence-Pylinac-Module/"
    - Starshot: "https://kaptandatasolutions.github.io/2024-10-06-Starshot-Pylinac-Module/"
    - Winston-Lutz 2D & 3D: "https://kaptandatasolutions.github.io/2024-10-06-Winston-lutz-2D-and-3D"
    - Image Test Generator: "https://kaptandatasolutions.github.io/2024-10-06-Image-generator-Pylinac-Module"
    
  Portfolio of App's 🚀: "https://kaptan-data.streamlit.app/"

################
# --- Logo --- #
################

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/avatar-icon.png"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
#title-img: /path/to/image


#####################################
# --- Footer social media links --- #
#####################################

# Select the social network links that you want to show in the footer.
# You can change the order that they show up on the page by changing the order here.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "https://kaptandatasolutions.github.io/contact/"
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  facebook: KaptanDataSolutions
  github: kaptandatasolutions
  twitter: KaptanData
  patreon: KaptanData
  youtube: "@KaptanDataSolutions"
  whatsapp: +33677264831
  Portfolio: "https://kaptan-data.streamlit.app/"
#  reddit: yourname or r/yoursubreddit
  linkedin: /company/kaptan-data-solutions/
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname
#  mastodon: instance.url/@username
#  bluesky: yourname
#  ORCID: your ORCID ID
#  google-scholar: your google scholar
#  discord: "invite_code" or "users/userid" or "invite/invite_code"
#  kaggle: yourname
#  hackerrank: yourname
#  gitlab: yourname
#  itchio: yourname
#  untappd: yourname

# If you want your website to generate an RSS feed, provide a description
# The URL for the feed will be https://<your_website>/feed.xml
rss-description: This website is proof that we're interested in everything to do with technology, and that we're always on the lookout for new innovations and advances in science.

###########################
# --- General options --- #
###########################

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  youtube : true
  patreon : true
  Portfolio : true
  vk: false
  
# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "KDS"

# Add the website title to the title of every page
title-on-all-pages: true

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: true

# Add a button in the footer to edit the current page. Only works if your website is hosted on GitHub
edit_page_button: False

# Allow sub-menu items (second-level navigation menu items) to be longer than the top-level menu
# If this setting is off, then long sub-menu words might get cut off
# See https://github.com/daattali/beautiful-jekyll/issues/765 to understand the issue this setting can solve
navbar-var-length: false

# The keywords to associate with your website, for SEO purposes
#keywords: "my,list,of,keywords"

######################################
# --- Colours / background image --- #
######################################

# Personalize the colours in your website. Colour values can be any valid CSS colour

#Couleur d'arrière-plan de la page principale
page-col: "#FFFFFF"
text-col: "#2a262f" 
#Couleur des liens
link-col: "#cd23dc"
#Couleur des liens au survol
hover-col: "#f549f4"
#Couleur d'arrière-plan de la barre de navigation
navbar-col: "#966dd5"
navbar-text-col: "#FFFFFF"
navbar-border-col: "#DDDDDD"
#Couleur du texte dans la barre de navigation
footer-col: "#966dd5"
#Couleur d'arrière-plan du pied de page
footer-text-col: "#FFFFFF"
#Couleur des liens dans le pied de page
footer-link-col: "#FFFFFF"
#Couleur des liens au survol dans le pied de page
footer-hover-col: "#f549f4"

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# Suggest a colour for mobile browsers to use as the browser's theme. This is only supported by a few mobile browsers.
#mobile-theme-col: "#0085A1"

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
#site-css:
#  - "/assets/css/custom-styles.css"

# If you have common JavaScript files that should be included in every page, list them here
#site-js:
#  - "/assets/js/custom-script.js"

#################################
# --- Web Analytics Section --- #
#################################

# Fill in your Google Analytics tag ID (or "Measurement ID") to track your website usage
gtag: "G-MX5ZJFPTBX"

# Fill in your Cloudflare Analytics beacon token to track your website using Cloudflare Analytics
#cloudflare_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.
#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# Google Universal Analytics ID -- deprecated
# As of July 2023 this is no longer supported by Google! If you are still using `google_analytics`,
# you should switch to using the `gtag` field above instead.
#google_analytics: "UA-XXXXXXXX-X"

####################
# --- Comments --- #
####################

# To use Disqus comments, sign up to https://disqus.com and fill in your Disqus shortname (NOT the userid)
#disqus: ""

# To use Facebook Comments, create a Facebook app and fill in the Facebook App ID
#fb_comment_id: ""

# To use CommentBox, sign up for a Project ID on https://commentbox.io
commentbox: "5721091683123200-proj" # Project ID, e.g. "5694267682979840-proj"

# To use Utterances comments: (0) uncomment the following section, (1) fill in
# "repository" (make sure the repository is public), (2) Enable Issues in your repository,
# (3) Install the Utterances app in your repository https://github.com/apps/utterances
# See more details about the parameters below at https://utteranc.es/
#utterances:
#  repository: # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  issue-term: title   # Mapping between blog posts and GitHub issues
#  theme: github-light # Utterances theme
#  label: blog-comments # Label that will be assigned to GitHub Issues created by Utterances

# To use Staticman comments, uncomment the following section. You may leave the reCaptcha
# section commented if you aren't using reCaptcha for spam protection.
# Using Staticman requires advanced knowledge, please consult
# https://github.com/eduardoboucas/staticman/ and https://staticman.net/ for further
# instructions. For any support with staticman please direct questions to staticman and
# not to BeautifulJekyll.
#staticman:
#  repository : # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  branch     : master # If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
#  endpoint   : # URL of your deployment, with a trailing slash eg. "https://<your-api>/v3/entry/github/"
#  reCaptcha:   # (optional, set these parameters in `staticman.yml` as well)
#    siteKey  : # You need to apply for a site key on Google
#    secret   : # Encrypt your password by going to https://<your-own-api>/v3/encrypt/<your-site-secret>

# To use giscus comments:
# (0) Uncomment the following giscus section, (1) Enable Discussions in your GitHub repository,
# (2) Install the giscus app in your repository (details at https://giscus.app),
# (3) Fill in *all* the parameters below
# See more details about giscus and each of the following parameters at https://giscus.app
#giscus:
#  hostname: giscus.app # Replace with your giscus instance's hostname if self-hosting
#  repository: # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  repository-id: # ID of your repository, retrieve this info from https://giscus.app
#  category: Announcements # Category name of your GitHub Discussion posts
#  category-id: # ID of your category, retrieve this info from https://giscus.app
#  mapping: pathname
#  reactions-enabled: 1
#  emit-metadata: 0
#  theme: light

################
# --- Misc --- #
################

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Facebook App ID
#fb_app_id: ""

#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

# Output options (more information on Jekyll's site)
timezone: "Europe/Paris"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
# Ajoutez cette ligne à votre _config.yml si ce n'est pas déjà fait
extracss: /assets/css/custom.css
